### ISSUE TITLE
 ZO training of the Android 关于ZO训练的安卓部署

### ISSUE THREAD

**Issue by leeyy2020** [leigao97/PRGE#1]
你好我本地尝试跑了一下项目，注意到安卓实机ZO训练部分没有包含在仓库内，请问后续还有开源计划吗。 
Hello, I tried to run the project locally and noticed that the ZO training part of the Android real machine is not included in the repo. Is there any open-source plan in the future?
@leigao97 @Amir-zsh

**Comment by leigao97** [comment]
Hi @leeyy2020, thank you for your interest. For now, we only implmented the "[dual-forwarding lora](https://github.com/leigao97/PRGE/blob/main/android/models/lora_android.py)" module that encodes the ZO algorithm and the "rand.op" to generate the noise when executing the module on the device. Note that when enabling the dual-forwarding lora, some operators are offloaded to CPU backend, such as where_op, rand_op, and etc, and we need to [exclude them from the NPU backend](https://github.com/leigao97/PRGE/blob/main/android/qnn.py#L100C9-L100C25) when exporting. We don't have an end-to-end training piepeline for now, but we plan to include a toy training demo in the next a few weeks, such that given a single input batch, the model should be able to converge on that.

**Comment by leeyy2020** [comment]
> Hi @leeyy2020, thank you for your interest. For now, we only implmented the "[dual-forwarding lora](https://github.com/leigao97/PRGE/blob/main/android/models/lora_android.py)" module that encodes the ZO algorithm and the "rand.op" to generate the noise when executing the module on the device. Note that when enabling the dual-forwarding lora, some operators are offloaded to CPU backend, such as where_op, rand_op, and etc, and we need to [exclude them from the NPU backend](https://github.com/leigao97/PRGE/blob/main/android/qnn.py#L100C9-L100C25) when exporting. We don't have an end-to-end training piepeline for now, but we plan to include a toy training demo in the next a few weeks, such that given a single input batch, the model should be able to converge on that.
> 
> 

ok got it and thanks for your reply
